# Generated by Django 6.0.3 on 2026-03-13 15:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("popcornbucket", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="review",
            name="created_at",
            field=models.DateTimeField(
                default=datetime.datetime(2026, 3, 13, 15, 31, 49, 565185)
            ),
        ),
    ]
