# Generated by Django 5.2.12 on 2026-03-13 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('popcornbucket', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='film',
            name='id',
        ),
        migrations.AddField(
            model_name='film',
            name='film_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
