# Generated by Django 6.0.3 on 2026-03-16 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "popcornbucket",
            "0002_remove_film_poster_url_film_poster_film_tmdb_id_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="review",
            name="down_votes",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="review",
            name="up_votes",
            field=models.IntegerField(default=0),
        ),
    ]
