# Generated by Django 5.2.12 on 2026-03-13 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('popcornbucket', '0002_remove_film_id_film_film_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='film',
            name='poster_url',
        ),
        migrations.AddField(
            model_name='film',
            name='poster',
            field=models.ImageField(blank=True, upload_to='film_posters/'),
        ),
    ]
