# Generated by Django 6.0.3 on 2026-03-21 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("popcornbucket", "0002_friendship"),
    ]

    operations = [
        migrations.AlterField(
            model_name="friendship",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
