# Generated by Django 5.2.12 on 2026-03-21 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('popcornbucket', '0003_alter_film_id_alter_genre_id_alter_review_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cinema',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('website', models.URLField(blank=True)),
                ('films', models.ManyToManyField(blank=True, related_name='cinemas', to='popcornbucket.film')),
            ],
        ),
    ]
