# Generated by Django 5.2.12 on 2026-03-13 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('popcornbucket', '0003_remove_film_poster_url_film_poster'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='tmdb_id',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='film',
            name='poster',
            field=models.ImageField(blank=True, null=True, upload_to='film_posters/'),
        ),
    ]
