# Generated by Django 5.2.12 on 2026-03-21 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('popcornbucket', '0003_review_down_votes_review_up_votes'),
        ('popcornbucket', '0004_cinema'),
    ]

    operations = [
    ]
